[build]
  base = "frontend/"
  command = "yarn build"
  publish = "build/"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn start"
  port = 3000
  targetPort = 3000